[tool.poetry]
name = "quirck"
version = "2023.1"
description = "Personalized Docker Assignment Platform"
authors = ["Nikita Sychev"]

[tool.poetry.dependencies]
python = "^3.10"
starlette = "^0.37.2"
uvicorn = "^0.30.1"
Jinja2 = "^3.1.4"
python-multipart = "^0.0.9"
aioboto3 = "^13.1.0"
httpx = "^0.27.0"
SQLAlchemy = {version = "^2.0.31", extras = ["asyncio", "mypy"]}
asyncpg = "^0.29.0"
gunicorn = "^22.0.0"
itsdangerous = "^2.2.0"
PyJWT = {extras = ["crypto"], version = "^2.8.0"}
cryptography = "^42.0.8"
aiodocker = "^0.22.0"
Starlette-WTF = "^0.4.5"
pytz = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
